// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Api;

#nullable disable

namespace WebApplication1.Api.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("WebApplication1.Api.Question", b =>
                {
                    b.Property<int>("soru_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("alan_bilgisi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("dogru_cevap")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("soru_dersi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("soru_id");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("WebApplication1.Api.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Correct_answers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Total_questions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Wrong_answers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Wrong_questions_Ids")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("is_student")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("is_teacher")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
